### PR TITLE
Add a Datasets class and tests

### PR DESCRIPTION
**Pull request by sgillies**
Also move other classes to submodules.

Very preliminary.

### CODE REVIEW

**Comment by sgillies** [comment]
Thanks for getting me straightened out with tokens, @emilymcafee @willwhite! I'm in your API, fetching all the features.

```
$ mbx features sgillies 0b87ffb3 > 0b87ffb3.json
```

**Comment by sgillies** [comment]
Demo of round-tripping features from rio-shapes through the Dataset API: https://gist.github.com/sgillies/369b580df78839d15c46.

**Comment by sgillies** [comment]
All caught up with master. I'm still uncertain about the names of the CLI commands and API methods.

**Comment by willwhite** [comment]
What about them @sgillies ?

**Comment by sgillies** [comment]
@willwhite I'm just debating with myself over stuff like `retrieve_feature(id)` vs `get_feature(id)` vs `feature(id)` and `update_feature(id, val)` vs `set_feature(id, val)` vs `feature(id, val)`. Trying to come up with something close to the ideal fit for Python on the first try :)

**Comment by perrygeo** [comment]
Heads up: [Create dataset should return 201](https://github.com/mapbox/api-core/issues/5214)

**Comment by sgillies** [comment]
Closing. Related work continues in #80.

**Pull request closed without merging**
