### PR TITLE
Refactor to produce a base service class.

### LINKED ISSUE #100: Caching
We might want to add optional caching via https://pypi.python.org/pypi/requests-cache

This would allow clients to store raw responses locally and reduce the burden on the API, particularly when developing and testing where the requests are likely to be repetitive.

### PR DESCRIPTION
**Pull request by sgillies**
The base service class can use an HTTP cache.

Closes #100.

### CODE REVIEW

**Comment by sgillies** [comment]
Along the way, I eliminated two class methods, one of which I turned into the `mapbox.service.base.Session()` function. Uppercase name because it mimics the `requests.Session()` constructor.

I'm testing the optional cache in `tests/test_directions.py` only, but as it's very generalized that should cover it.

@perrygeo can you give this a review tomorrow?

**Comment by perrygeo** [comment]
This looks good. Passing the cache object to the service constructor is the way to go and should support https://github.com/mapbox/mapbox-cli-py/issues/43 easily. :+1:

**Comment by sgillies** [comment]
@perrygeo please merge for me when you can.

**Comment by sgillies** [comment]
Fwiw, pip uses (a vendorized) cachecontrol: https://github.com/pypa/pip/tree/master/pip/_vendor.

Very important note: there is a CacheControl bug in the way https://github.com/ionrock/cachecontrol/issues/95. Until it's resolved, we won't be able to cache chunked HTTP responses and as far as I can tell, all our APIs use chunked transfer encodings.

**Pull request merged**
