### PR TITLE
geocoder v5

### PR DESCRIPTION
**Pull request by sbma44**
- updates endpoints
- rounds precision of `proximity` flag & reverse geocoding
- tests for ^^^ 

@sgillies mind have a quick look?

### CODE REVIEW

**Comment by sgillies** [comment]
Looks good to me. We should have a new release, yes?

**Comment by sbma44** [comment]
whoops, my tab got out of date and I didn't see that you merged before I made a 0.1.1 commit to the branch. I'll leave the version bumping to you; that commit can disappear into git limbo.

**Comment by sgillies** [comment]
I'm going to make it a 0.2.

**Comment by sbma44** [comment]
fine by me!

**Pull request merged**
