### PR TITLE
Tilesets API

### PR DESCRIPTION
**Pull request by critical-path**
This attempts to address #152.  I would be happy to make changes to the code, tests, etc.  Thank you!

### CODE REVIEW

**Comment by sgillies** [comment]
@critical-path there are a few conflicts to resolve after the merger of #235. My schedule is full for the rest of this week, but I think I'll be able to review this next week.

**Comment by critical-path** [comment]
@sgillies 

I have resolved the merge conflict.  Please let me know if you would like additional changes.  Thank you!

**Comment by sgillies** [comment]
Thanks @critical-path ! Tilesets API is the most crucial of these PRs to review, I think, unless you have other priorities.

**Comment by critical-path** [comment]
@sgillies 

Thank you for the opportunity to contribute to this project!  My apologies if I tagged you too many times - I am still learning Github workflows and conventions.

I defer to you on prioritization.  It seems very reasonable to review Tilesets first.  Thank you!

**Pull request closed without merging**
