### PR TITLE
Upload API

### PR DESCRIPTION
**Pull request by perrygeo**
Initial implementation of the Upload API. Needs some review, see overview in [example usage](https://github.com/mapbox/mapbox-sdk-py/blob/3a11e2d55ab4f1333c15820aab54aec87368a6c9/mapbox/services/upload.py#L10)

### CODE REVIEW

**Comment by perrygeo** [comment]
Currently the only blocker I see is:

* [ ] Mocking S3

Any others?

**Comment by sgillies** [comment]
Needs more coverage, but that's a side effect of the lack of s3 mocks?

Giving it a try...

**Comment by perrygeo** [comment]
Here's [the bug](https://github.com/spulec/moto/issues/440) that's preventing me from using `moto` to mock s3 calls. Conceptually it looks promising but the issues are littered with similar problems and there are no real docs.

**Comment by sgillies** [comment]
I'm happy to report that this totally works. I created a token with `uploads:*` scopes at https://www.mapbox.com/account/apps/, uploaded the Rasterio testing file to my account like this

```python
>>> from mapbox import Uploader
>>> conxn = Uploader('sgillies', access_token='MY_TOKEN')
>>> resp = conxn.upload('/Users/sean/code/rasterio/tests/data/RGB.byte.tif', 'RGB-byte-tif')
>>> resp.text
u'{"id":"cifzrlur163cyuikrm5gm9yyv","name":null,"complete":false,"error":null,"created":"2015-10-20T19:29:34.270Z","modified":"2015-10-20T19:29:34.270Z","tileset":"sgillies.RGB-byte-tif","owner":"sgillies","progress":0}'
>>> conxn.status('cifzrlur163cyuikrm5gm9yyv').text
u'{"id":"cifzrlur163cyuikrm5gm9yyv","name":null,"complete":true,"error":null,"created":"2015-10-20T19:29:34.270Z","modified":"2015-10-20T19:29:45.002Z","tileset":"sgillies.RGB-byte-tif","owner":"sgillies","progress":1}'
```
and here's the map I made of the results:

https://a.tiles.mapbox.com/v4/sgillies.nom02cb5/page.html?access_token=pk.eyJ1Ijoic2dpbGxpZXMiLCJhIjoiWUE2VlZVcyJ9.OITHkb1GHNh9nvzIfUc9QQ#9/24.6870/-77.8725

**Comment by sgillies** [comment]
@perrygeo once you've added to the readme, let's merge this and look at mocking staging and credentials afterwards.

**Pull request merged**
