### PR TITLE
Styles API

### PR DESCRIPTION
**Pull request by critical-path**
This attempts to address #72.  I would be happy to make changes to the code, tests, etc.  Thank you!

### CODE REVIEW

**Comment by critical-path** [comment]
@sgillies 

This is ready for review.  Thank you!

**Comment by sgillies** [comment]
@critical-path no, thank you! Review of this PR will be a delayed a bit.

**Comment by dwohlfahrt** [comment]
can I ask why this branch was deleted?  was really looking forward to having the styles api functionality in this package.

**Comment by sgillies** [comment]
@dwohlfahrt development of this project is paused with no ETA to restart. It's fair for @critical-path to move on. For what it's worth, GitHub is still holding on to the patch https://patch-diff.githubusercontent.com/raw/mapbox/mapbox-sdk-py/pull/245.diff and you are welcome to use it in your projects until this project resumes.

**Pull request closed without merging**
