### PR TITLE
add bypass flag for uploads service

### PR DESCRIPTION
**Pull request by mapsam**
Adds a flag alongside patch for bypassing mbtiles uploads (which requires the feature to be enabled on a user's account).

cc @ivovandongen @ian29 @sgillies

### CODE REVIEW

**Comment by mapsam** [comment]
Not sure why the travis hook hasn't reported 🍏 - https://travis-ci.org/mapbox/mapbox-sdk-py/builds/502140081 is passing!

**Comment by mapsam** [comment]
@sgillies the responses package worked out really nice - although I mostly copied from the `patch` tests ;) 

Question about releases - do you tag on specific commits? Or would you like me to update the version + changelog in this branch, merge into master, then tag the latest commit as 0.18.0?

**Comment by mapsam** [comment]
Just updated the CHANGES and mapbox/__init__.py version @sgillies! Looks like a tagged commit is the way to release? Very cool 😄

**Comment by sgillies** [comment]
I've been merging to master before I tag, but the release process https://github.com/mapbox/mapbox-sdk-py/blob/master/HOWTO_RELEASE.md doesn't care whether you merge before or after the tag. It's up to you.

**Pull request merged**
