### PR TITLE
remove vendorized polyline, add dep

### LINKED ISSUE #74: Problem with polyline module dependencies
@perrygeo I've traced our issues with failing tests on Travis to the `polyline` module requiring exactly one version of `six`. As shown by `pipdeptree`:

```polyline==1.1 -> six [required: ==1.8.0, installed: 1.8.0]```

Everybody would be better off if the requirement were `six>=1.8.0`. I'm going to pursue this upstream and pin the version locally for testing purposes.

### PR DESCRIPTION
**Pull request by perrygeo**
https://github.com/frederickjansen/polyline is 👌  and address our earlier concerns, resolves #74 

And importantly, the official version squashes some precision bugs that would have slumbered.

### CODE REVIEW

**Comment by perrygeo** [comment]
Troubling results, it seems that the encoding is different depending on python version. 😬 

```bash
$ python3.5 -c "import polyline; print(polyline.encode([[-112.084004, 36.05322], [-112.083914, 36.053573], [-112.083965, 36.053845]]))"
~kbkTss`{EQeAHw@

$ python2.7 -c "import polyline; print(polyline.encode([[-112.084004, 36.05322], [-112.083914, 36.053573], [-112.083965, 36.053845]]))"
~kbkTss`{EQeAJw@

**Comment by perrygeo** [comment]
Until https://github.com/frederickjansen/polyline/pull/3 is resolved and merged and a new version is released (presumably `polyline==1.4.0`), this is on hold.

**Comment by frederickjansen** [comment]
@perrygeo I released v1.3.1 to fix the issue. Thanks for the heads up!

**Comment by perrygeo** [comment]
@sgillies this is good to go, getting consistent behavior with all python versions.

Thanks @frederickjansen for getting the fix out so quickly and for pointing out our coordinate order bug. We're happy to be using your lib!

**Pull request merged**
